# Generated by Django 6.0.4 on 2026-05-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
